version: '3.1'

services:
  db:
    container_name: db
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: contactsdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8011:80"  # Disamakan sesuai kebutuhan
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    depends_on:
      - db

  api:
    build: .
    container_name: api-contact-form
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mariadb_data:
